Models/ApplicationContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Awards.Models
{
    public class ApplicationContext : DbContext
    {
        public ApplicationContext(DbContextOptions<ApplicationContext> options) : base(options)
        {
        }
        public DbSet<User> Users { get; set; }
        public DbSet<Award> Awards { get; set; }
        public DbSet<UsersAwards> UsersAwards { get; set; }
    }
}

Models/Award.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Awards.Models
{
    public class Award
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Awards.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Awards.Models
{
    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime BirthDate { get; set; }
        public int Age { get; set; }
        [NotMapped]
        public List<Award> Awards { get; set; }
    }
}

Models/UsersAwards.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Awards.Models
{
    public class UsersAwards
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public User User { get; set; }
        public int AwardId { get; set; }
        public Award Award { get; set; }
    }
}

Models/ViewModels/MainPage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Awards.Models.ViewModels
{
    public class MainPage
    {
        public List<User> Users { get; set; }
        public List<Award> Awards { get; set; }
    }
}

Controllers/AwardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Awards.Models;
using Microsoft.AspNetCore.Mvc;

namespace Awards.Controllers
{
    public class AwardController : Controller
    {
        ApplicationContext _context;
        public AwardController(ApplicationContext context)
        {
            _context = context;
        }
        public IActionResult AddAward()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddAward(Award award)
        {
            _context.Awards.Add(award);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Awards.Models;
using Awards.Models.ViewModels;
using System.Data.SqlClient;

namespace Awards.Controllers
{
    public class HomeController : Controller
    {
        ApplicationContext _context;
        public HomeController(ApplicationContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var mainPage = new MainPage();
            mainPage.Users = _context.Users.ToList();
            mainPage.Awards = _context.Awards.ToList();
            var usersAwards = _context.UsersAwards.ToList();
            foreach (var user in mainPage.Users)
            {
                user.Awards = new List<Award>();
                foreach (var connecter in usersAwards)
                {
                    if (connecter.UserId == user.Id)
                    {
                        user.Awards.AddRange(mainPage.Awards.Where(a => a.Id == connecter.AwardId).ToList());
                    }                 
                }
            }
            return View(mainPage);
        }
        
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Awards.Models;
using Microsoft.AspNetCore.Mvc;

namespace Awards.Controllers
{
    public class UserController : Controller
    {
        ApplicationContext _context;
        public UserController(ApplicationContext context)
        {
            _context = context;
        }
        public IActionResult AddUser()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddUser(User user)
        {
            user.Age = user.BirthDate.Year - DateTime.Today.Year;
            user.Age *= -1;
            _context.Users.Add(user);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public IActionResult DeleteUser(int Id)
        {
            var user = _context.Users.FirstOrDefault(u=>u.Id == Id);
            _context.Remove(user);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
        public IActionResult EditUser(int Id)
        {
            var user = _context.Users.FirstOrDefault(u => u.Id == Id);
            return View(user);
        }
        [HttpPost]
        public IActionResult EditUser(User user)
        {
            user.Age = user.BirthDate.Year - DateTime.Today.Year;
            user.Age *= -1;
            _context.Users.Update(user);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public IActionResult AwardUser(int userId, int awardId)
        {
            _context.UsersAwards.Add(new UsersAwards() { UserId = userId, AwardId = awardId });
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Award/AddAward.cshtml
@model Awards.Models.Award
@{
    ViewData["Title"] = "AddAward";
}

<h1>AddAward</h1>

<form asp-action="AddAward">
    <div class="form-group">
        <label asp-for="Title">Name</label>
        <input asp-for="Title" type="text" class="form-control" placeholder="Введите название награды">
    </div>
    <div class="form-group">
        <label asp-for="Description">Password</label>
        <input asp-for="Description" type="text" class="form-control" placeholder="Описание награды">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Views/Home/Index.cshtml
@model Awards.Models.ViewModels.MainPage
@{
    ViewData["Title"] = "Home Page";
}

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Handle</th>
            <th scope="col">Изменить</th>
            <th scope="col">Наградить</th>
            <th scope="col">Награды</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Users.Count() != 0)
        {
            @foreach (var item in Model.Users)
            {
        <tr>
            <th scope="row">@item.Id</th>
            <td>@item.Name</td>
            <td>@item.Age</td>
            <td>
                <form asp-action="DeleteUser" asp-controller="User" method="post">
                    <input type="hidden" name="Id" value="@item.Id" />
                    <input type="submit" value="Удалить пользователя" />
                </form>
            </td>
            <td>
                <form asp-action="EditUser" asp-controller="User" method="get">
                    <input type="hidden" name="Id" value="@item.Id" />
                    <input type="submit" value="Изменить данные" />
                </form>
            </td>
            <td>
                <form asp-action="AwardUser" asp-controller="User" method="post">
                    <input type="hidden" name="userId" value="@item.Id" />
                    <select name="awardId">
                        @foreach (var award in Model.Awards)
                        {
                            <option value="@award.Id">@award.Title</option>
                        }
                    </select>
                    <input type="submit" value="Наградить" />
                </form>
            </td>
            <td>
                @if (item.Awards != null)
                {
                    @foreach (var userAwards in item.Awards)
                    {
                        <p>@userAwards.Title</p>
                    }
                }
            </td>
        </tr>
            }
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Awards</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Awards</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="AddUser">Добавить пользователя</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Award" asp-action="AddAward">Добавить награду</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Awards - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/User/AddUser.cshtml
@model Awards.Models.User
@{
    ViewData["Title"] = "AddUser";
}

<h1>AddUser</h1>
<form asp-action="AddUser">
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" type="text" class="form-control"  placeholder="Enter name">        
    </div>
    <div class="form-group">
        <label asp-for="BirthDate">Password</label>
        <input asp-for="BirthDate" type="date" class="form-control"  placeholder="Birth date">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Views/User/EditUser.cshtml
@model Awards.Models.User
@{
    ViewData["Title"] = "EditUser";
}

<h1>EditUser</h1>
<form asp-action="EditUser" method="post">
    <input type="hidden" asp-for="Id" value="@Model.Id" />
    <input type="hidden" asp-for="Age" value="@Model.Age" />
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" type="text" class="form-control" placeholder="Enter name" value="@Model.Name">
    </div>
    <div class="form-group">
        <label asp-for="BirthDate">Password</label>
        <input asp-for="BirthDate" type="date" class="form-control" placeholder="Birth date" value="@Model.BirthDate">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>